/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
  public const val activity_compose: String = "androidx.activity:activity-compose:_"

  public const val animation: String = "androidx.compose.animation:animation:_"

  public const val androidx_compose_compiler_compiler: String =
    "androidx.compose.compiler:compiler:_"

  public const val foundation: String = "androidx.compose.foundation:foundation:_"

  public const val material3: String = "androidx.compose.material3:material3:_"

  public const val material3_window_size_class: String =
    "androidx.compose.material3:material3-window-size-class:_"

  public const val androidx_compose_material_material: String =
    "androidx.compose.material:material:_"

  public const val material_icons_extended: String =
    "androidx.compose.material:material-icons-extended:_"

  public const val ui: String = "androidx.compose.ui:ui:_"

  public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

  public const val ui_test_manifest: String = "androidx.compose.ui:ui-test-manifest:_"

  public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

  public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

  public const val ui_util: String = "androidx.compose.ui:ui-util"

  public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

  public const val customview: String = "androidx.customview:customview:_"

  public const val customview_poolingcontainer: String =
    "androidx.customview:customview-poolingcontainer:_"

  public const val viewbinding: String = "androidx.databinding:viewbinding:_"

  public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

  public const val lifecycle_viewmodel_compose: String =
    "androidx.lifecycle:lifecycle-viewmodel-compose:_"

  public const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

  public const val navigation_fragment_ktx: String =
    "androidx.navigation:navigation-fragment-ktx:_"

  public const val room_compiler: String = "androidx.room:room-compiler:_"

  public const val room_ktx: String = "androidx.room:room-ktx:_"

  public const val room_runtime: String = "androidx.room:room-runtime:_"

  public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

  public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

  public const val customactivityoncrash: String = "cat.ereza:customactivityoncrash:_"

  public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

  public const val accompanist_permissions: String =
    "com.google.accompanist:accompanist-permissions:_"

  public const val accompanist_swiperefresh: String =
    "com.google.accompanist:accompanist-swiperefresh:_"

  public const val accompanist_systemuicontroller: String =
    "com.google.accompanist:accompanist-systemuicontroller:_"

  public const val com_google_android_material_material: String =
    "com.google.android.material:material:_"

  public const val firebase_analytics_ktx: String = "com.google.firebase:firebase-analytics-ktx"

  public const val firebase_bom: String = "com.google.firebase:firebase-bom:_"

  public const val firebase_crashlytics_gradle: String =
    "com.google.firebase:firebase-crashlytics-gradle:_"

  public const val firebase_crashlytics_ktx: String =
    "com.google.firebase:firebase-crashlytics-ktx"

  public const val firebase_messaging: String = "com.google.firebase:firebase-messaging"

  public const val google_services: String = "com.google.gms:google-services:_"

  public const val timber: String = "com.jakewharton.timber:timber:_"

  public const val onesignal: String = "com.onesignal:OneSignal:_"

  public const val moshi: String = "com.squareup.moshi:moshi:_"

  public const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:_"

  public const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

  public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

  public const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

  public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

  public const val de_fayard_buildsrclibs_gradle_plugin: String =
    "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

  public const val onesignal_gradle_plugin: String =
    "gradle.plugin.com.onesignal:onesignal-gradle-plugin:_"

  public const val compressor: String = "id.zelory:compressor:_"

  public const val coil_compose: String = "io.coil-kt:coil-compose:_"

  public const val detekt_formatting: String = "io.gitlab.arturbosch.detekt:detekt-formatting:_"

  public const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
    "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

  public const val koin_android: String = "io.insert-koin:koin-android:_"

  public const val koin_androidx_compose: String = "io.insert-koin:koin-androidx-compose:_"

  public const val mockk: String = "io.mockk:mockk:_"

  public const val junit_junit: String = "junit:junit:_"

  public const val toolbar_compose: String = "me.onebone:toolbar-compose:_"

  public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

  public const val org_jetbrains_kotlin_android_gradle_plugin: String =
    "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:_"

  public const val kotlin_annotation_processing_gradle: String =
    "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

  public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

  public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"
}
