# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
      
jobs:
  build:
    name: Check Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "api_key=\"\"" >> local.properties
      - name: Add Url Demo
        run: echo "url_demo=\"\"" >> local.properties
      - name: Add Url Prod
        run: echo "url_prod=\"\"" >> local.properties
      - name: Run Check Versions
        run: ./gradlew dependencyUpdates
      - name: Create Folder
        run: mkdir -p dependencyUpdates
      - name: Upload Report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: dependencyUpdates/report.html 
